### ISSUE TITLE
Can not log in to hosted account

### ISSUE THREAD

**Issue by deweyhulsey** [Axosoft/MacStopWatch#3]
Running OS X 10.10 and Axosoft Stopwatch 1.1.1.
I enter my hosted OnTime url in teh API settings and try to log in, to receive this error:
![Image of error message](http://i.imgur.com/sxSlLkF.png)

I can sign in normally from the web interface.

**Comment by luistheone** [comment]
I have the same problem (cant login) with macbook pro OSX 10.10.2
I have the API enable, i can work with the windows version in windows.
Thanks
